apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: always-firing-test
  namespace: monitoring
  labels:
    release: prometheus   # THIS IS CRITICAL
spec:
  groups:
  - name: test.rules
    rules:
    - alert: AlwaysFiringTest
      expr: vector(1)
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Always firing test alert"
        impact: "None – test only"
        action: "Verify end-to-end alerting"
